### ISSUE TITLE
Mojave compilation problem

### ISSUE THREAD

**Issue by awelc** [facebook/redex#409]
I am trying to build ReDex from sources on Mojave and I am having some trouble. I am using tip of the master branch (6fd7ccebee29e65a43cac5e51e64c67d89dbc5fc), my Xcode version is 10.1.0, and I am using boost library version 1.70.0. 

I needed to specify jsoncpp and boost paths explicitly for some reason as config was not able to pick them up but I am not sure if this makes any difference:
```
autoreconf -ivf && ./configure LDFLAGS='-L/usr/local/opt/jsoncpp/lib -L/usr/local/opt/boost/lib' CXXFLAGS='-I/usr/local/opt/jsoncpp/include -I/usr/local/opt/boost/include'
```

In any case, configuration step passes without problems but then during compilation via `make` I am getting the following error, and I am not sure if it's due to the compiler version problem, the boost library version problem, some sparta problem (I tried building it separately resulting in the same error), or something completely different:
```
/usr/local/opt/boost/include/boost/variant/detail/apply_visitor_unary.hpp:98:33: error: no matching function for call to object of type '(lambda at
      ./sparta/include/DisjointUnionAbstractDomain.h:95:26)'
        typedef decltype(true ? boost::declval< Visitor& >()( boost::declval< value_t >() )
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I would really appreciate some help.

**Comment by awelc** [comment]
I think I figured it out eventually. It's the boost library problem - there is some weird issue introduced in 1.70. I solved it by reverting to a previous version:
```
brew uninstall boost
brew install boost@1.59
```
But then you need to use `--with-boost=/usr/local/opt/boost@1.59` to get it to pick up all the boost components (regex, etc.)

I will leave it up to you to decide whether to close this issue in case you want to consider making ReDex work with boost 1.70.

**Comment by justinjhendrick** [comment]
Glad you figured it out. Go ahead and leave the issue open. We should figure out what exactly changed in the newer versions of boost and how to work with/around it.

**Comment by emma0303** [comment]
This seems the same as the bug described in https://github.com/facebookincubator/fizz/issues/33. Copy pasta from comments in https://github.com/boostorg/variant/issues/69 -> `The fix will be in Boost 1.71. Until then you can manually apply the patch from #68 to the 1.70 version`
