### ISSUE TITLE
build in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by TCGOGOGO** [facebook/redex#243]
/usr/include/boost/regex/v4/perl_matcher.hpp:383: undefined reference to `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
collect2: error: ld returned 1 exit status
make[1]: *** [redex-all] 错误 1

**Comment by TCGOGOGO** [comment]
g++ (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by justinjhendrick** [comment]
Which version of boost are you using?

**Comment by TCGOGOGO** [comment]
boost_1_65_0.zip

**Comment by TCGOGOGO** [comment]
boost_1_64_0

**Comment by justinjhendrick** [comment]
We saw this same issue a while ago in #211 but we didn't solve it then either. I'm unable to reproduce it on my end, but I've requested an ubuntu machine with which to test it. I should have that machine by next week. Sorry for the delay.

**Comment by justinjhendrick** [comment]
In the mean time, let's see if we can figure this out remotely :D 

Do you have boost::regex installed? How did you install boost?

https://packages.ubuntu.com/trusty/libboost-all-dev should get what we need but let's see if we can verify by looking in your /lib directories.

Could you please run this command:
```
jhendrick-mbp:~$ ld -v 10
```

Here's my output:
```
@(#)PROGRAM:ld  PROJECT:ld64-278.4
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
Library search paths:
	/usr/lib
	/usr/local/lib
Framework search paths:
	/Library/Frameworks/
	/System/Library/Frameworks/
ld: file not found: 10
```
I'm interested in the "Library search paths:". For each path in that list, could you run this command:

```
ls /<path>/*boost_regex*
```

So, for me that would look like this:
```
jhendrick-mbp:~$ ls /usr/lib/*boost_regex*
ls: /usr/lib/*boost_regex*: No such file or directory
jhendrick-mbp:~$ ls /usr/local/lib/*boost_regex*
/usr/local/lib/libboost_regex-mt.a     /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_regex.a        /usr/local/lib/libboost_regex.dylib
```

**Comment by justinjhendrick** [comment]
Another possibility. Have you updated your boost version since the last time you compiled redex? `make clean && make -j4` would fix it if this were the issue.

**Comment by justinjhendrick** [comment]
I can't reproduce this on ubuntu 16.04. Could you add this flag `-Wl,--verbose` [here](https://github.com/facebook/redex/blob/master/Makefile.am#L224) and send a paste of the full output, please

**Comment by justinjhendrick** [comment]
Closing due to age
