### ISSUE TITLE
        acc_vec[i] = PlacementNewUniquePtr<Accumulator>(new (aligned_alloc(

### ISSUE THREAD

**Issue by SireAI** [facebook/redex#438]
build redex stage

./libredex/DexClass.h:1167:11: warning: unused variable 'dmethods' [-Wunused-variable]
    auto& dmethods = get_dmethods();
          ^
In file included from libredex/ApiLevelChecker.cpp:13:
./libredex/Walkers.h:438:62: error: use of undeclared identifier 'aligned_alloc'
        acc_vec[i] = PlacementNewUniquePtr<Accumulator>(new (aligned_alloc(
                                                             ^
1 warning and 1 error generated.

**Comment by ssj933** [comment]
Hi! Sorry for the trouble, we noticed this issue and is working on fix. Will reply back when the fix is out.

**Comment by hansionit** [comment]
+1

**Comment by hansionit** [comment]
./libredex/DexClass.h:1167:11: warning: unused variable 'dmethods'
      [-Wunused-variable]
    auto& dmethods = get_dmethods();
          ^
In file included from libredex/ApiLevelChecker.cpp:13:
./libredex/Walkers.h:438:62: error: use of undeclared identifier 'aligned_alloc'
        acc_vec[i] = PlacementNewUniquePtr<Accumulator>(new (aligned_alloc(
                                                             ^
1 warning and 1 error generated.

**Comment by justinjhendrick** [comment]
Yeah, sorry, the build was broken on Macs recently. It was just fixed early this morning: 0ad0e2a070a1580a37b14ff817dde2404d0b0413

**Comment by SireAI** [comment]
I cloned and rebuild redex agian on mac,a error happend again   in the progress @justinjhendrick 



In file included from libredex/Debug.cpp:24:
In file included from /usr/local/include/boost/stacktrace.hpp:15:
In file included from /usr/local/include/boost/stacktrace/frame.hpp:20:
In file included from /usr/local/include/boost/stacktrace/safe_dump_to.hpp:217:
/usr/local/include/boost/stacktrace/detail/collect_unwind.ipp:33:2: error: 
      "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define
      `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if
      _Unwind_Backtrace is available without `_GNU_SOURCE`."
#error "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `...
 ^
1 error generated.

**Comment by justinjhendrick** [comment]
Hmmm... That seems like a different error, possibly introduced by e92ab38663366812d35ec49bc97089ffdabb4ed2?

**Comment by SireAI** [comment]
the branch of stable works normally,but the way of command to get the source of redex  does not work .The command is :
   git clone https://github.com/facebook/redex.git

what's the differenence?

**Comment by hansionit** [comment]
retry

sudo make install

/usr/local/include/boost/stacktrace/detail/collect_unwind.ipp:33:2: error:
      "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define
      `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if
      _Unwind_Backtrace is available without `_GNU_SOURCE`."
#error "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `...
 ^
1 error generated.

**Comment by justinjhendrick** [comment]
> what's the difference [between master and the stable branch]?

`stable` is our long-lived release branch. About 4 times a year, we make a release and copy from the master branch into stable. And we also add bug-fixes and other cherry-picks to stable regularly.

**Comment by justinjhendrick** [comment]
> /usr/local/include/boost/stacktrace/detail/collect_unwind.ipp:33:2: error:
> "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define
> `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if
> _Unwind_Backtrace is available without `_GNU_SOURCE`."
> #error "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `...
> ^
> 1 error generated.

Should be fixed by ec1e34e420f0a7c4cbdf0c0c13dce5d6a2b5eaf8

**Comment by hansionit** [comment]
How to clone the stable branch?

**Comment by SireAI** [comment]
Thank you for your patience, I tried again ,and redex builds successfully !

when I run redex command with proguard  to optimise apk  ,just like :

`redex  -c default.config  input.apk  -o output.apk -P proguard-rules.pro  -m mapping.txt --sign -s test.keysotre -a test -p 123456 `

a error comes out ：




libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::error_info_injector<RedexException>: libredex/VirtualScope.cpp:886: void ClassScopes::build_interface_scopes(): assertion `scopes.size() > 0' failed.

0   redex-all                           0x0000000105c08472 _Z23crash_backtrace_handleri + 50
1   libsystem_platform.dylib            0x00007fff6ad0fb5d _sigtramp + 29
2   libc++abi.dylib                     0x00007fff67db1998 GCC_except_table51 + 216
3   libsystem_c.dylib                   0x00007fff6abc96a6 abort + 127
4   libc++abi.dylib                     0x00007fff67da4641 __cxa_bad_cast + 0
5   libc++abi.dylib                     0x00007fff67da47c7 _ZL25default_terminate_handlerv + 243
6   libobjc.A.dylib                     0x00007fff69357eeb _ZL15_objc_terminatev + 105
7   libc++abi.dylib                     0x00007fff67db019e _ZSt11__terminatePFvvE + 8
8   libc++abi.dylib                     0x00007fff67daff86 __cxa_get_exception_ptr + 0
9   libc++abi.dylib                     0x00007fff67da2f99 __cxa_get_globals + 0
10  redex-all                           0x0000000105c08a7b _Z11assert_failPKcS0_jS0_10RedexErrorS0_z + 939
11  redex-all                           0x0000000105dccded _ZN11ClassScopes22build_interface_scopesEv + 989
12  redex-all                           0x0000000105dcc45b _ZN11ClassScopesC2ERKNSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEE + 603
13  redex-all                           0x0000000105dc1a19 _ZN10TypeSystemC2ERKNSt3__16vectorIP8DexClassNS0_9allocatorIS3_EEEE + 25
14  redex-all                           0x0000000105802d04 _ZN17FinalInlinePassV28run_passERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFilesR11PassManager + 1604
15  redex-all                           0x0000000105cc755e _ZN11PassManager10run_passesERNSt3__16vectorI8DexStoreNS0_9allocatorIS2_EEEER11ConfigFiles + 6158
16  redex-all                           0x0000000105bb6adb main + 5547
17  libdyld.dylib                       0x00007fff6ab243d5 start + 1
Traceback (most recent call last):
  File "/tmp/redex.1e4quX/redex.py", line 1105, in <module>
    run_redex(args)
  File "/tmp/redex.1e4quX/redex.py", line 1083, in run_redex
    run_redex_binary(state)
  File "/tmp/redex.1e4quX/redex.py", line 414, in run_redex_binary
    if run():
  File "/tmp/redex.1e4quX/redex.py", line 399, in run
    % script_filenames
RuntimeError: redex-all crashed with exit code -6! You can re-run it under gdb by running /tmp/redex.1e4quX/redex-gdb-9cwv56gn.sh or under lldb by running /tmp/redex.1e4quX/redex-lldb-_9nsp6p3.sh

**Comment by emma0303** [comment]
This issue seems convoluted. In the future, I would open a different one, as this issue is totally different than the first one.

The issue that you mentioned above usually happens if the input apk is missing referenced classes .. Is the input.apk ok?

**Comment by emma0303** [comment]
Realized this issue was already mentioned in #437. Closing this one as it was solved. Copied my previous question there too.
